import { execFile } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';
import path from 'path';
import os from 'os';
import { randomUUID } from 'crypto';

const execFileAsync = promisify(execFile);

// Pipeline stage 2: "Is this PDF's text selectable, or is it a scan?"
//
// Heuristic: try extracting text directly. If what comes back is empty or
// just whitespace/junk, treat it as a scanned/image-only PDF and hand off
// to OCR.
//
// This shells out to `pdftotext`/`pdfinfo` (poppler-utils — already a
// system dependency for the OCR stage) instead of using the `pdf-parse`
// npm package. `pdf-parse` bundles a very old, unmaintained pdf.js build
// (v1.10.100, ~2017) that throws "bad XRef entry" on plenty of spec-valid,
// modern PDFs (confirmed against files generated by pdfkit and by hand —
// poppler and qpdf both parse them without complaint), which would
// misclassify perfectly good PDFs as corrupted. poppler-utils is actively
// maintained and far more robust here.

const MIN_MEANINGFUL_CHARS = 20;

export async function checkTextLayer(pdfBuffer) {
  const tempPdfPath = path.join(os.tmpdir(), `textlayer-${randomUUID()}.pdf`);
  await fs.writeFile(tempPdfPath, pdfBuffer);

  try {
    let pageCount = 0;
    try {
      const { stdout: infoOut } = await execFileAsync('pdfinfo', [tempPdfPath]);
      const match = infoOut.match(/^Pages:\s+(\d+)/m);
      if (match) pageCount = parseInt(match[1], 10);
    } catch (err) {
      // pdfinfo failing to even read the file is the strongest signal this
      // PDF is corrupted/unreadable.
      return { readable: false, hasTextLayer: false, text: '', pageCount: 0, error: 'corrupted' };
    }

    let text;
    try {
      const { stdout } = await execFileAsync('pdftotext', ['-layout', tempPdfPath, '-']);
      text = stdout;
    } catch (err) {
      return { readable: false, hasTextLayer: false, text: '', pageCount, error: 'corrupted' };
    }

    const cleaned = text.replace(/\s+/g, ' ').trim();
    const hasTextLayer = cleaned.length >= MIN_MEANINGFUL_CHARS;

    return {
      readable: true,
      hasTextLayer,
      text: hasTextLayer ? text : '',
      pageCount
    };
  } finally {
    await fs.rm(tempPdfPath, { force: true });
  }
}
